#!/bin/sh

if [ -x "`which update-desktop-database 2>/dev/null`" ]; then
    update-desktop-database -q || true
fi

if [ -x "`which update-menus 2>/dev/null`" ]; then
    update-menus || true
fi

exit 0
